defaults :
  - modulus_default
  - arch:
      - fully_connected
      - deeponet
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
  
arch:
  branch:
    nr_layers: 4
    layer_size: 128
  trunk:
    nr_layers: 4
    layer_size: 128
  deeponet:
    output_keys: u
    
scheduler:
  decay_rate: 0.9
  decay_steps: 10000
  
training:
  rec_validation_freq: 1000
  max_steps: 10000
  
batch_size:
  train: 10000
  validation: 100
  
save_filetypes: "np"